### ISSUE TITLE
resources.geojson boundaries do not match actual extent of the point clouds

### ISSUE THREAD

**Issue by diego-gris** [hobuinc/usgs-lidar#67]
The project boundaries in the resources.geojson file do not match the extent of the point cloud. This causes issues when trying to determine the source of lidar data in the se boundaries because I would think I can get lidar data on those locations, but I end up with an empty point cloud. Is there a reason for these extra borders around the point clouds?
Example below: point cloud vs. geojson boundaries in green.
<img width="824" alt="image" src="https://github.com/hobuinc/usgs-lidar/assets/98782844/645238ca-4b1f-43f4-a9b3-f2f3c11a73b5">

**Comment by connormanning** [comment]
The boundaries are computed at quite a low resolution since there is so much data to analyze here. You could compute them for a given resource yourself if you need higher resolution - that code all runs in a github action so you can follow along with how these boundaries are generated and increase the resolution to something suitable for your use-case.  If you know that your particular dataset is rectangular, you could also simply look at the extents in the `ept.json` metadata for that resource.
