### ISSUE TITLE
Are USGS  lidar points on AWS in WGS 84?

### ISSUE THREAD

**Issue by yplin317** [hobuinc/usgs-lidar#72]
Hello,

  When trying to download point clouds from S3 (e.g., https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_ClarkCo_2_B22/ept.json), the header specifies that the points are in EPSG:3857 (WGS 84). However, with some cross checks against Google Earth, there seems to be ~2M discrepancy horizontally. From [wiki](https://en.wikipedia.org/wiki/North_American_Datum) it mentions the differences between NAD 83 and WGS 84 is 2.2M, so I suspect maybe the true horizontal datum in the EPT file should be NAD 83 rather than WGS 84?

**Comment by jstoker74** [comment]
Do you know the elevation source in google earth? IIRC they used SRTM?

**Comment by yplin317** [comment]
Yes you are right (https://support.google.com/earth/thread/6672201/google-earth-pro-vertical-reference?hl=en).

But why is that relevant in this context?

**Comment by cjcrosby** [comment]
FWIW, I grabbed a small bit of this dataset over Boulder City, NV via OpenTopography and I don't see any evidence of an offset in Google Earth or Maps: https://portal.opentopography.org/usgsOutput?jobId=usgs1715355297827

This suite of notebooks may be helpful for you to validate the composition of your PDAL pipeline(s): https://github.com/OpenTopography/OT_3DEP_Workflows

**Comment by jstoker74** [comment]
SRTM has a documented vertical accuracy of around +/-4m compared to surveyed data (examples: https://doi.org/10.1038%2Fsrep41672; https://doi.org/10.1515/geo-2022-0455; https://doi.org/10.1016/j.asej.2017.01.007; https://doi.org/10.3133/ofr20141008; https://doi.org/10.3390/rs14040940, eg.) Since I was not sure exactly how you came to the 2.2m bias number I was making an assumption (apologies if incorrect) suggesting that maybe a couple checks using google earth might not be statistically significant enough to figure out if there is an actual vertical bias that was based on misrepresented datums, due to the uncertainty in measurements in SRTM. Not saying you are wrong here, just know it is hard to use SRTM to validate high-accuracy data.

**Comment by yplin317** [comment]
>SRTM has a documented vertical accuracy of around +/-4m compared to surveyed data...

@jstoker74 , got it. But the issue I reported above is a ~2M discrepancy horizontally, not vertically :) .

**Comment by jstoker74** [comment]
Sorry, conflated typical vertical comparisons for horizontal. Horizontal accuracies on elevation data are even more difficult to assess than vertical. A quick search that looked at horizontal accuracy puts SRTM at 15-20m, at 1 arc Second pixel (30m). So it is not surprising to me edges wouldn't match perfectly at the levels you are talking. Still not sure if you can attribute this 2m offset to WGS84-NAD83 mismatch, or call it a true bias unless you've sampled many areas?  And if you are comparing the image data in google earth to the lidar, and they are using SRTM to georeference the imagery then you are using a much lower res/lower accuracy dataset to validate a higher resolution higher accuracy one, even if the imagery is high resolution in looks, it is not in georeferencing.  I think what I'm trying to say (poorly) is that google earth imagery isn't a good validation dataset for precise geolocation 'ground truth'. But since I'm not sure how the imagery in google earth is georeferenced/rectified I was assuming they used SRTM, which may be incorrect. I may be completely misunderstanding how you are assessing these things as well. Going to shut up now ;-)

**Comment by yplin317** [comment]
Thank you @jstoker74, your comments make sense. I basically download an area of lidar points from USGS into a las file, and then rasterize it using `pdal translate las_file geotiff_file` command. Then I imported the geotiff into Google Earth, and saw a ~2M judder when toggle on and off the geotiff image (please see the attached gif). And  you are right, the imagery in Google earth is not in ortho view, so my comparison is meaningless. Thanks again for taking your time answering my questions!
  
![boulder](https://github.com/hobuinc/usgs-lidar/assets/6982742/f67a3074-99c5-4d01-b61e-408cc7a8537a)
